name: plantjake
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  image_picker: ^0.8.5+3
  logger: ^2.3.0
  flutter_tflite: ^1.0.1
  file_picker: ^8.0.5
  path_provider: ^2.0.9
  shared_preferences: ^2.2.3
  cached_network_image: ^3.2.0
  intl: ^0.17.0
#  flutter_launcher_icons: ^0.11.0
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
    
# flutter_icons:
 # android: true
 # image_path: "assets/icon/app_icon.png"
 # min_sdk_android: 21
 # background_color: "#1A4D2E"

flutter:
  uses-material-design: true

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf
#    - family: Roboto
#        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/icon/app_icon.png
    - assets/PlantJake.png
    - assets/ilustrasi.png
    - assets/icon_camera.png
    - assets/icon_upload.png
    - assets/15model_unquant.tflite
    - assets/15labels.txt
    - assets/descriptions.txt


  

